### ISSUE TITLE
Fatal error: Uncaught PDOExcemption

### ISSUE THREAD

**Issue by n-christie** [rubenarslan/formr_dev_docker#1]
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'formr_db.survey_users' doesn't exist in /formr/application/DB.php:253
Stack trace:
#0 /formr/application/DB.php(253): PDO->prepare('SELECT count(*)...')
#1 /formr/bin/add_user.php(26): DB->count('survey_users')
#2 {main}
  thrown in /formr/application/DB.php on line 253
Mon, 27 Nov 2023 13:28:02 +0100 Error 500: A fatal error occured and your request could not be completed. Contact site admins with these details <br />
Error [1] in application/DB.php line 253 <br />
 GRACEFUL-GOPHER-2727

**Comment by n-christie** [comment]
Found this one, build.sh, line 81.  Change "mysql" command to "mariadb". 

sudo docker exec -i formr_db sh -c "exec mysql -uroot -p${MARIADB_ROOT_PASSWORD}" < mysql/dbinitial/schema.sql

sudo docker exec -i formr_db sh -c "exec mariadb -uroot -p${MARIADB_ROOT_PASSWORD}" < mysql/dbinitial/schema.sql
